name: fullstack-spring-react

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: exemplo
    ports:
      - "5432:5432"