### Listar todos os produtos
GET http://localhost:8080/api/produtos

### Buscar produtos
GET http://localhost:8080/api/produtos?nome=exemplo&precoMinimo=50.0&categoria=eletronicos&ordenarPor=nome&ordem=asc&pagina=1&tamanho=10
Content-Type: application/json

### Buscar produto por ID
GET http://localhost:8080/api/produtos/1
Content-Type: application/json

### Criar novo produto
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Produto Exemplo",
  "descricao": "Descrição de exemplo",
  "preco": 100.0,
  "categoria": "Eletrônicos"
}

### Atualizar o produto (PUT)
PUT http://localhost:8080/api/produtos/1
Content-Type: application/json

{
  "nome": "Produto Atualizado",
  "descricao": "Nova descrição",
  "preco": 120.0,
  "categoria": "Escritório"
}

### Atualizar parcialmente o produto (PATCH)
PATCH http://localhost:8080/api/produtos/1
Content-Type: application/json

{
  "preco": 150.0
}

### Excluir produto
DELETE http://localhost:8080/api/produtos/1
Content-Type: application/json
